### ISSUE TITLE
some question

### ISSUE THREAD

**Issue by caoxu915683474** [brightmart/nlu_sim#2]
thanks for sharing this good work!
how much will these features improve your f1 score?
```
1)n-gram similiarity(blue score for n-gram=1,2,3...);

2) get length of questions, difference of length

3) how many words are same, how many words are unique

4) question 1,2 start with how/why/when(wei shen me,zenme，ruhe，weihe）

5）edit distance

6) cos similiarity using bag of words for sentence representation(combine tfidf with word embedding from word2vec,fasttext)

7) manhattan_distance,canberra_distance,minkowski_distance,euclidean_distance

```

**Comment by brightmart** [comment]
hi,


n-gram similarity,edit distance,cos similiarity, manhattan_distance,canberra_distance and other distance is useful.


you can use deep learning to learn, but with these features and normalize these features, performance can be improved.


as there is saying:



      features define the up bound of your performance, model is used to approach this bound.





bright.


________________________________
发件人: caoxu915683474 <notifications@github.com>
发送时间: 2018年7月3日 10:33
收件人: brightmart/nlu_sim
抄送: Subscribed
主题: [brightmart/nlu_sim] some question (#2)


thanks for sharing this good work!
how much will these features improve your f1 score?

1)n-gram similiarity(blue score for n-gram=1,2,3...);

2) get length of questions, difference of length

3) how many words are same, how many words are unique

4) question 1,2 start with how/why/when(wei shen me,zenme，ruhe，weihe）

5）edit distance

6) cos similiarity using bag of words for sentence representation(combine tfidf with word embedding from word2vec,fasttext)

7) manhattan_distance,canberra_distance,minkowski_distance,euclidean_distance



―

**Comment by caoxu915683474** [comment]
@brightmart 
Thanks for your smart answer!

**Comment by caoxu915683474** [comment]
@brightmart 
hi XuLiang !  I have used the feature you provide, but the result got worse, and not a little. So I don't know whether these features are useful or not?

**Comment by brightmart** [comment]
how do you use the features?

**Comment by caoxu915683474** [comment]
@brightmart 
我是直接在最后输出的位置先过了层线性的映射，然后拼接到之前模型的输出前了。

**Comment by brightmart** [comment]
you can check my mix model where I used additional features.
